version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: prompt-polyglot-api:local
    ports:
      - "8080:8080"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: prompt-polyglot-web:local
    environment:
      PUBLIC_API_BASE: http://api:8080
    ports:
      - "5173:5173"
    depends_on:
      - api
